version: "3.6"
services:
  ziyan:
    image: "10.7.0.117:9095/mabo_group/base_application/doctopus_ziyan:latest"
    container_name: "avl-ziyan"
    # restart: always
    working_dir: /usr/mabo/ziyan
    command: python  manage.py -t ziyan
    depends_on: 
      - redis
    volumes:
      - ./ziyan:/usr/mabo/ziyan
    networks:
      - avl-ziyan


      
networks:
  avl-ziyan: